/*
 * FormKiQ HTTP API Formkiq API: Document Management Platform API using JWT Authentication
 *
 * The version of the OpenAPI document: 1.12.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import com.formkiq.client.model.DocumentSearchItemMeta;
import com.formkiq.client.model.DocumentSearchItemTag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentSearch
 */
public class DocumentSearchTest {
  private final DocumentSearch model = new DocumentSearch();

  /**
   * Model tests for DocumentSearch
   */
  @Test
  public void testDocumentSearch() {
    // TODO: test DocumentSearch
  }

  /**
   * Test the property 'text'
   */
  @Test
  public void textTest() {
    // TODO: test text
  }

  /**
   * Test the property 'meta'
   */
  @Test
  public void metaTest() {
    // TODO: test meta
  }

  /**
   * Test the property 'tag'
   */
  @Test
  public void tagTest() {
    // TODO: test tag
  }

  /**
   * Test the property 'documentIds'
   */
  @Test
  public void documentIdsTest() {
    // TODO: test documentIds
  }

}
