/*
 * FormKiQ HTTP API Formkiq API: Document Management Platform API using JWT Authentication
 *
 * The version of the OpenAPI document: 1.12.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentAction
 */
public class DocumentActionTest {
  private final DocumentAction model = new DocumentAction();

  /**
   * Model tests for DocumentAction
   */
  @Test
  public void testDocumentAction() {
    // TODO: test DocumentAction
  }

  /**
   * Test the property 'status'
   */
  @Test
  public void statusTest() {
    // TODO: test status
  }

  /**
   * Test the property 'type'
   */
  @Test
  public void typeTest() {
    // TODO: test type
  }

  /**
   * Test the property 'userId'
   */
  @Test
  public void userIdTest() {
    // TODO: test userId
  }

  /**
   * Test the property 'parameters'
   */
  @Test
  public void parametersTest() {
    // TODO: test parameters
  }

}
