/*
 * FormKiQ HTTP API Formkiq API: Document Management Platform API using JWT Authentication
 *
 * The version of the OpenAPI document: 1.12.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetConfigurationResponse
 */
public class GetConfigurationResponseTest {
  private final GetConfigurationResponse model = new GetConfigurationResponse();

  /**
   * Model tests for GetConfigurationResponse
   */
  @Test
  public void testGetConfigurationResponse() {
    // TODO: test GetConfigurationResponse
  }

  /**
   * Test the property 'chatGptApiKey'
   */
  @Test
  public void chatGptApiKeyTest() {
    // TODO: test chatGptApiKey
  }

  /**
   * Test the property 'maxContentLengthBytes'
   */
  @Test
  public void maxContentLengthBytesTest() {
    // TODO: test maxContentLengthBytes
  }

  /**
   * Test the property 'maxDocuments'
   */
  @Test
  public void maxDocumentsTest() {
    // TODO: test maxDocuments
  }

  /**
   * Test the property 'maxWebhooks'
   */
  @Test
  public void maxWebhooksTest() {
    // TODO: test maxWebhooks
  }

}
