/*
 * FormKiQ API JWT Formkiq API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.16.1 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import com.formkiq.client.model.MappingAttributeLabelMatchingType;
import com.formkiq.client.model.MappingAttributeMetadataField;
import com.formkiq.client.model.MappingAttributeSourceType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MappingAttribute
 */
public class MappingAttributeTest {
  private final MappingAttribute model = new MappingAttribute();

  /**
   * Model tests for MappingAttribute
   */
  @Test
  public void testMappingAttribute() {
    // TODO: test MappingAttribute
  }

  /**
   * Test the property 'attributeKey'
   */
  @Test
  public void attributeKeyTest() {
    // TODO: test attributeKey
  }

  /**
   * Test the property 'sourceType'
   */
  @Test
  public void sourceTypeTest() {
    // TODO: test sourceType
  }

  /**
   * Test the property 'defaultValue'
   */
  @Test
  public void defaultValueTest() {
    // TODO: test defaultValue
  }

  /**
   * Test the property 'defaultValues'
   */
  @Test
  public void defaultValuesTest() {
    // TODO: test defaultValues
  }

  /**
   * Test the property 'labelTexts'
   */
  @Test
  public void labelTextsTest() {
    // TODO: test labelTexts
  }

  /**
   * Test the property 'labelMatchingType'
   */
  @Test
  public void labelMatchingTypeTest() {
    // TODO: test labelMatchingType
  }

  /**
   * Test the property 'metadataField'
   */
  @Test
  public void metadataFieldTest() {
    // TODO: test metadataField
  }

  /**
   * Test the property 'validationRegex'
   */
  @Test
  public void validationRegexTest() {
    // TODO: test validationRegex
  }

}
