/*
 * FormKiQ API JWT FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.19.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import com.formkiq.client.model.OpenSearchSnapshotFailure;
import com.formkiq.client.model.OpenSearchSnapshotShard;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OpenSearchSnapshot
 */
public class OpenSearchSnapshotTest {
  private final OpenSearchSnapshot model = new OpenSearchSnapshot();

  /**
   * Model tests for OpenSearchSnapshot
   */
  @Test
  public void testOpenSearchSnapshot() {
    // TODO: test OpenSearchSnapshot
  }

  /**
   * Test the property 'snapshot'
   */
  @Test
  public void snapshotTest() {
    // TODO: test snapshot
  }

  /**
   * Test the property 'uuid'
   */
  @Test
  public void uuidTest() {
    // TODO: test uuid
  }

  /**
   * Test the property 'version'
   */
  @Test
  public void versionTest() {
    // TODO: test version
  }

  /**
   * Test the property 'indices'
   */
  @Test
  public void indicesTest() {
    // TODO: test indices
  }

  /**
   * Test the property 'shards'
   */
  @Test
  public void shardsTest() {
    // TODO: test shards
  }

  /**
   * Test the property 'failures'
   */
  @Test
  public void failuresTest() {
    // TODO: test failures
  }

  /**
   * Test the property 'state'
   */
  @Test
  public void stateTest() {
    // TODO: test state
  }

  /**
   * Test the property 'startTime'
   */
  @Test
  public void startTimeTest() {
    // TODO: test startTime
  }

  /**
   * Test the property 'startTimeInMillis'
   */
  @Test
  public void startTimeInMillisTest() {
    // TODO: test startTimeInMillis
  }

  /**
   * Test the property 'endTime'
   */
  @Test
  public void endTimeTest() {
    // TODO: test endTime
  }

  /**
   * Test the property 'endTimeInMillis'
   */
  @Test
  public void endTimeInMillisTest() {
    // TODO: test endTimeInMillis
  }

  /**
   * Test the property 'durationInMillis'
   */
  @Test
  public void durationInMillisTest() {
    // TODO: test durationInMillis
  }

}
