/*
 * FormKiQ API JWT FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.19.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.formkiq.client.invoker.JSON;

/**
 * DocumentCertificationParameterStore
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-03-14T20:35:46.352811-05:00[America/Winnipeg]",
    comments = "Generator version: 7.20.0")
public class DocumentCertificationParameterStore {
  public static final String SERIALIZED_NAME_PKCS12_BUNDLE_PARAM = "pkcs12BundleParam";
  @SerializedName(SERIALIZED_NAME_PKCS12_BUNDLE_PARAM)
  @javax.annotation.Nonnull
  private String pkcs12BundleParam;

  public static final String SERIALIZED_NAME_PKCS12_PASSWORD_PARAM = "pkcs12PasswordParam";
  @SerializedName(SERIALIZED_NAME_PKCS12_PASSWORD_PARAM)
  @javax.annotation.Nonnull
  private String pkcs12PasswordParam;

  public DocumentCertificationParameterStore() {}

  public DocumentCertificationParameterStore pkcs12BundleParam(
      @javax.annotation.Nonnull String pkcs12BundleParam) {
    this.pkcs12BundleParam = pkcs12BundleParam;
    return this;
  }

  /**
   * SSM Parameter Store Key containing the PKCS#12/PFX bundle.
   * 
   * @return pkcs12BundleParam
   */
  @javax.annotation.Nonnull
  public String getPkcs12BundleParam() {
    return pkcs12BundleParam;
  }

  public void setPkcs12BundleParam(@javax.annotation.Nonnull String pkcs12BundleParam) {
    this.pkcs12BundleParam = pkcs12BundleParam;
  }


  public DocumentCertificationParameterStore pkcs12PasswordParam(
      @javax.annotation.Nonnull String pkcs12PasswordParam) {
    this.pkcs12PasswordParam = pkcs12PasswordParam;
    return this;
  }

  /**
   * SSM Parameter Store Key containing the PKCS#12/PFX password.
   * 
   * @return pkcs12PasswordParam
   */
  @javax.annotation.Nonnull
  public String getPkcs12PasswordParam() {
    return pkcs12PasswordParam;
  }

  public void setPkcs12PasswordParam(@javax.annotation.Nonnull String pkcs12PasswordParam) {
    this.pkcs12PasswordParam = pkcs12PasswordParam;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentCertificationParameterStore documentCertificationParameterStore =
        (DocumentCertificationParameterStore) o;
    return Objects.equals(this.pkcs12BundleParam,
        documentCertificationParameterStore.pkcs12BundleParam)
        && Objects.equals(this.pkcs12PasswordParam,
            documentCertificationParameterStore.pkcs12PasswordParam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkcs12BundleParam, pkcs12PasswordParam);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentCertificationParameterStore {\n");
    sb.append("    pkcs12BundleParam: ").append(toIndentedString(pkcs12BundleParam)).append("\n");
    sb.append("    pkcs12PasswordParam: ").append(toIndentedString(pkcs12PasswordParam))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("pkcs12BundleParam", "pkcs12PasswordParam"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields =
        new HashSet<String>(Arrays.asList("pkcs12BundleParam", "pkcs12PasswordParam"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to
   *         DocumentCertificationParameterStore
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!DocumentCertificationParameterStore.openapiRequiredFields.isEmpty()) { // has required
                                                                                  // fields but JSON
                                                                                  // element is null
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The required field(s) %s in DocumentCertificationParameterStore is not found in the empty JSON string",
            DocumentCertificationParameterStore.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!DocumentCertificationParameterStore.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The field `%s` in the JSON string is not defined in the `DocumentCertificationParameterStore` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }

    // check to make sure all required properties/fields are present in the JSON string
    for (String requiredField : DocumentCertificationParameterStore.openapiRequiredFields) {
      if (jsonElement.getAsJsonObject().get(requiredField) == null) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The required field `%s` is not found in the JSON string: %s", requiredField,
            jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if (!jsonObj.get("pkcs12BundleParam").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
          "Expected the field `pkcs12BundleParam` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("pkcs12BundleParam").toString()));
    }
    if (!jsonObj.get("pkcs12PasswordParam").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
          "Expected the field `pkcs12PasswordParam` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("pkcs12PasswordParam").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!DocumentCertificationParameterStore.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'DocumentCertificationParameterStore' and its
                     // subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<DocumentCertificationParameterStore> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(DocumentCertificationParameterStore.class));

      return (TypeAdapter<T>) new TypeAdapter<DocumentCertificationParameterStore>() {
        @Override
        public void write(JsonWriter out, DocumentCertificationParameterStore value)
            throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public DocumentCertificationParameterStore read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }

  /**
   * Create an instance of DocumentCertificationParameterStore given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DocumentCertificationParameterStore
   * @throws IOException if the JSON string is invalid with respect to
   *         DocumentCertificationParameterStore
   */
  public static DocumentCertificationParameterStore fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DocumentCertificationParameterStore.class);
  }

  /**
   * Convert an instance of DocumentCertificationParameterStore to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

