/*
 * FormKiQ API JWT FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.19.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import java.util.Objects;
import com.formkiq.client.model.SystemInferenceModel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.formkiq.client.invoker.JSON;

/**
 * GetSystemInferenceModelsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-05-05T20:07:54.830243-05:00[America/Winnipeg]",
    comments = "Generator version: 7.22.0")
public class GetSystemInferenceModelsResponse {
  public static final String SERIALIZED_NAME_INFERENCE_MODELS = "inferenceModels";
  @SerializedName(SERIALIZED_NAME_INFERENCE_MODELS)
  @javax.annotation.Nullable
  private List<SystemInferenceModel> inferenceModels = new ArrayList<>();

  public GetSystemInferenceModelsResponse() {}

  public GetSystemInferenceModelsResponse inferenceModels(
      @javax.annotation.Nullable List<SystemInferenceModel> inferenceModels) {
    this.inferenceModels = inferenceModels;
    return this;
  }

  public GetSystemInferenceModelsResponse addInferenceModelsItem(
      SystemInferenceModel inferenceModelsItem) {
    if (this.inferenceModels == null) {
      this.inferenceModels = new ArrayList<>();
    }
    this.inferenceModels.add(inferenceModelsItem);
    return this;
  }

  /**
   * List of system inference models
   * 
   * @return inferenceModels
   */
  @javax.annotation.Nullable
  public List<SystemInferenceModel> getInferenceModels() {
    return inferenceModels;
  }

  public void setInferenceModels(
      @javax.annotation.Nullable List<SystemInferenceModel> inferenceModels) {
    this.inferenceModels = inferenceModels;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSystemInferenceModelsResponse getSystemInferenceModelsResponse =
        (GetSystemInferenceModelsResponse) o;
    return Objects.equals(this.inferenceModels, getSystemInferenceModelsResponse.inferenceModels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inferenceModels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSystemInferenceModelsResponse {\n");
    sb.append("    inferenceModels: ").append(toIndentedString(inferenceModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("inferenceModels"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to
   *         GetSystemInferenceModelsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!GetSystemInferenceModelsResponse.openapiRequiredFields.isEmpty()) { // has required
                                                                               // fields but JSON
                                                                               // element is null
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The required field(s) %s in GetSystemInferenceModelsResponse is not found in the empty JSON string",
            GetSystemInferenceModelsResponse.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!GetSystemInferenceModelsResponse.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The field `%s` in the JSON string is not defined in the `GetSystemInferenceModelsResponse` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    if (jsonObj.get("inferenceModels") != null && !jsonObj.get("inferenceModels").isJsonNull()) {
      JsonArray jsonArrayinferenceModels = jsonObj.getAsJsonArray("inferenceModels");
      if (jsonArrayinferenceModels != null) {
        // ensure the json data is an array
        if (!jsonObj.get("inferenceModels").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
              "Expected the field `inferenceModels` to be an array in the JSON string but got `%s`",
              jsonObj.get("inferenceModels").toString()));
        }

        // validate the optional field `inferenceModels` (array)
        for (int i = 0; i < jsonArrayinferenceModels.size(); i++) {
          SystemInferenceModel.validateJsonElement(jsonArrayinferenceModels.get(i));
        } ;
      }
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!GetSystemInferenceModelsResponse.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'GetSystemInferenceModelsResponse' and its
                     // subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<GetSystemInferenceModelsResponse> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(GetSystemInferenceModelsResponse.class));

      return (TypeAdapter<T>) new TypeAdapter<GetSystemInferenceModelsResponse>() {
        @Override
        public void write(JsonWriter out, GetSystemInferenceModelsResponse value)
            throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public GetSystemInferenceModelsResponse read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }

  /**
   * Create an instance of GetSystemInferenceModelsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetSystemInferenceModelsResponse
   * @throws IOException if the JSON string is invalid with respect to
   *         GetSystemInferenceModelsResponse
   */
  public static GetSystemInferenceModelsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetSystemInferenceModelsResponse.class);
  }

  /**
   * Convert an instance of GetSystemInferenceModelsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

