/*
 * FormKiQ API JWT FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.19.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.model;

import java.util.Objects;
import com.formkiq.client.model.DocumentReviewStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.formkiq.client.invoker.JSON;

/**
 * UpdateDocumentReview
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-06-21T22:53:47.944205-05:00[America/Winnipeg]",
    comments = "Generator version: 7.23.0")
public class UpdateDocumentReview {
  public static final String SERIALIZED_NAME_REVIEW_STATUS = "reviewStatus";
  @SerializedName(SERIALIZED_NAME_REVIEW_STATUS)
  @javax.annotation.Nullable
  private DocumentReviewStatus reviewStatus;

  public static final String SERIALIZED_NAME_REQUIRED_DECISIONS = "requiredDecisions";
  @SerializedName(SERIALIZED_NAME_REQUIRED_DECISIONS)
  @javax.annotation.Nullable
  private Long requiredDecisions;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  @javax.annotation.Nullable
  private String comments;

  public UpdateDocumentReview() {}

  public UpdateDocumentReview reviewStatus(
      @javax.annotation.Nullable DocumentReviewStatus reviewStatus) {
    this.reviewStatus = reviewStatus;
    return this;
  }

  /**
   * Get reviewStatus
   * 
   * @return reviewStatus
   */
  @javax.annotation.Nullable
  public DocumentReviewStatus getReviewStatus() {
    return reviewStatus;
  }

  public void setReviewStatus(@javax.annotation.Nullable DocumentReviewStatus reviewStatus) {
    this.reviewStatus = reviewStatus;
  }


  public UpdateDocumentReview requiredDecisions(@javax.annotation.Nullable Long requiredDecisions) {
    this.requiredDecisions = requiredDecisions;
    return this;
  }

  /**
   * Number of decisions required to complete the review minimum: 1
   * 
   * @return requiredDecisions
   */
  @javax.annotation.Nullable
  public Long getRequiredDecisions() {
    return requiredDecisions;
  }

  public void setRequiredDecisions(@javax.annotation.Nullable Long requiredDecisions) {
    this.requiredDecisions = requiredDecisions;
  }


  public UpdateDocumentReview comments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
    return this;
  }

  /**
   * Review comments
   * 
   * @return comments
   */
  @javax.annotation.Nullable
  public String getComments() {
    return comments;
  }

  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDocumentReview updateDocumentReview = (UpdateDocumentReview) o;
    return Objects.equals(this.reviewStatus, updateDocumentReview.reviewStatus)
        && Objects.equals(this.requiredDecisions, updateDocumentReview.requiredDecisions)
        && Objects.equals(this.comments, updateDocumentReview.comments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reviewStatus, requiredDecisions, comments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDocumentReview {\n");
    sb.append("    reviewStatus: ").append(toIndentedString(reviewStatus)).append("\n");
    sb.append("    requiredDecisions: ").append(toIndentedString(requiredDecisions)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields =
        new HashSet<String>(Arrays.asList("reviewStatus", "requiredDecisions", "comments"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateDocumentReview
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    if (jsonElement == null) {
      if (!UpdateDocumentReview.openapiRequiredFields.isEmpty()) { // has required fields but JSON
                                                                   // element is null
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The required field(s) %s in UpdateDocumentReview is not found in the empty JSON string",
            UpdateDocumentReview.openapiRequiredFields.toString()));
      }
    }

    Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
    // check to see if the JSON string contains additional fields
    for (Map.Entry<String, JsonElement> entry : entries) {
      if (!UpdateDocumentReview.openapiFields.contains(entry.getKey())) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
            "The field `%s` in the JSON string is not defined in the `UpdateDocumentReview` properties. JSON: %s",
            entry.getKey(), jsonElement.toString()));
      }
    }
    JsonObject jsonObj = jsonElement.getAsJsonObject();
    // validate the optional field `reviewStatus`
    if (jsonObj.get("reviewStatus") != null && !jsonObj.get("reviewStatus").isJsonNull()) {
      DocumentReviewStatus.validateJsonElement(jsonObj.get("reviewStatus"));
    }
    if ((jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull())
        && !jsonObj.get("comments").isJsonPrimitive()) {
      throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
          "Expected the field `comments` to be a primitive type in the JSON string but got `%s`",
          jsonObj.get("comments").toString()));
    }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
      if (!UpdateDocumentReview.class.isAssignableFrom(type.getRawType())) {
        return null; // this class only serializes 'UpdateDocumentReview' and its subtypes
      }
      final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
      final TypeAdapter<UpdateDocumentReview> thisAdapter =
          gson.getDelegateAdapter(this, TypeToken.get(UpdateDocumentReview.class));

      return (TypeAdapter<T>) new TypeAdapter<UpdateDocumentReview>() {
        @Override
        public void write(JsonWriter out, UpdateDocumentReview value) throws IOException {
          JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
          elementAdapter.write(out, obj);
        }

        @Override
        public UpdateDocumentReview read(JsonReader in) throws IOException {
          JsonElement jsonElement = elementAdapter.read(in);
          validateJsonElement(jsonElement);
          return thisAdapter.fromJsonTree(jsonElement);
        }

      }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateDocumentReview given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateDocumentReview
   * @throws IOException if the JSON string is invalid with respect to UpdateDocumentReview
   */
  public static UpdateDocumentReview fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateDocumentReview.class);
  }

  /**
   * Convert an instance of UpdateDocumentReview to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

