/*
 * FormKiQ API JWT FormKiQ API: Document Management Platform API using OAuth(JWT) Authentication You
 * can find out more about FormKiQ at [https://formkiq.com](http://formkiq.com). ## Introduction
 * FormKiQ is an API-first (head-less), battle-tested document management API. The FormKiQ API
 * provides all the API endpoints to build your Perfect Document Management Platform. FormKiQ API
 * was built on top of [OpenAPI specification](https://www.openapis.org), so it is easy to use the
 * API spec file with any application that supports the OpenAPI specification. Open API OAuth
 * Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-jwt.yaml Open
 * API IAM Specification -
 * https://raw.githubusercontent.com/formkiq/formkiq-core/master/docs/openapi/openapi-iam.yaml ##
 * Authentication FormKiQ offers three forms of authentication: - OAuth(JWT) - AWS IAM - API Key
 *
 * The version of the OpenAPI document: 1.19.0 Contact: support@formkiq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */


package com.formkiq.client.api;

import com.formkiq.client.invoker.ApiCallback;
import com.formkiq.client.invoker.ApiClient;
import com.formkiq.client.invoker.ApiException;
import com.formkiq.client.invoker.ApiResponse;
import com.formkiq.client.invoker.Configuration;
import com.formkiq.client.invoker.Pair;
import com.formkiq.client.invoker.ProgressRequestBody;
import com.formkiq.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.formkiq.client.model.AddDocumentMetadataExtractionResponse;
import com.formkiq.client.model.GetDocumentDataClassificationResponse;
import com.formkiq.client.model.GetDocumentMetadataExtractionResponse;
import com.formkiq.client.model.SetDocumentDataClassificationRequest;
import com.formkiq.client.model.SetDocumentDataClassificationResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IntelligentDocumentProcessingApi {
  private ApiClient localVarApiClient;
  private int localHostIndex;
  private String localCustomBaseUrl;

  public IntelligentDocumentProcessingApi() {
    this(Configuration.getDefaultApiClient());
  }

  public IntelligentDocumentProcessingApi(ApiClient apiClient) {
    this.localVarApiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return localVarApiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.localVarApiClient = apiClient;
  }

  public int getHostIndex() {
    return localHostIndex;
  }

  public void setHostIndex(int hostIndex) {
    this.localHostIndex = hostIndex;
  }

  public String getCustomBaseUrl() {
    return localCustomBaseUrl;
  }

  public void setCustomBaseUrl(String customBaseUrl) {
    this.localCustomBaseUrl = customBaseUrl;
  }

  /**
   * Build call for addDocumentMetadataExtractionResult
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call addDocumentMetadataExtractionResultCall(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      final ApiCallback _callback) throws ApiException {
    String basePath = null;
    // Operation Servers
    String[] localBasePaths = new String[] {};

    // Determine Base Path to Use
    if (localCustomBaseUrl != null) {
      basePath = localCustomBaseUrl;
    } else if (localBasePaths.length > 0) {
      basePath = localBasePaths[localHostIndex];
    } else {
      basePath = null;
    }

    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/documents/{documentId}/metadataExtractionResults/{llmPromptEntityName}"
        .replace("{" + "documentId" + "}", localVarApiClient.escapeString(documentId.toString()))
        .replace("{" + "llmPromptEntityName" + "}",
            localVarApiClient.escapeString(llmPromptEntityName.toString()));

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (siteId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("siteId", siteId));
    }

    if (artifactId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("artifactId", artifactId));
    }

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {};
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    if (localVarContentType != null) {
      localVarHeaderParams.put("Content-Type", localVarContentType);
    }

    String[] localVarAuthNames = new String[] {"AWS4Auth"};
    return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
        localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
        localVarFormParams, localVarAuthNames, _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call addDocumentMetadataExtractionResultValidateBeforeCall(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      final ApiCallback _callback) throws ApiException {
    // verify the required parameter 'documentId' is set
    if (documentId == null) {
      throw new ApiException(
          "Missing the required parameter 'documentId' when calling addDocumentMetadataExtractionResult(Async)");
    }

    // verify the required parameter 'llmPromptEntityName' is set
    if (llmPromptEntityName == null) {
      throw new ApiException(
          "Missing the required parameter 'llmPromptEntityName' when calling addDocumentMetadataExtractionResult(Async)");
    }

    return addDocumentMetadataExtractionResultCall(documentId, llmPromptEntityName, siteId,
        artifactId, _callback);

  }

  /**
   * Add document&#39;s metadata extraction result Create a document Metadatq Extraction Result
   * attributes within a document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @return AddDocumentMetadataExtractionResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public AddDocumentMetadataExtractionResponse addDocumentMetadataExtractionResult(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId)
      throws ApiException {
    ApiResponse<AddDocumentMetadataExtractionResponse> localVarResp =
        addDocumentMetadataExtractionResultWithHttpInfo(documentId, llmPromptEntityName, siteId,
            artifactId);
    return localVarResp.getData();
  }

  /**
   * Add document&#39;s metadata extraction result Create a document Metadatq Extraction Result
   * attributes within a document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @return ApiResponse&lt;AddDocumentMetadataExtractionResponse&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public ApiResponse<AddDocumentMetadataExtractionResponse> addDocumentMetadataExtractionResultWithHttpInfo(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId)
      throws ApiException {
    okhttp3.Call localVarCall = addDocumentMetadataExtractionResultValidateBeforeCall(documentId,
        llmPromptEntityName, siteId, artifactId, null);
    Type localVarReturnType = new TypeToken<AddDocumentMetadataExtractionResponse>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * Add document&#39;s metadata extraction result (asynchronously) Create a document Metadatq
   * Extraction Result attributes within a document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call addDocumentMetadataExtractionResultAsync(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      final ApiCallback<AddDocumentMetadataExtractionResponse> _callback) throws ApiException {

    okhttp3.Call localVarCall = addDocumentMetadataExtractionResultValidateBeforeCall(documentId,
        llmPromptEntityName, siteId, artifactId, _callback);
    Type localVarReturnType = new TypeToken<AddDocumentMetadataExtractionResponse>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }

  /**
   * Build call for getAllDocumentMetadataExtractionResults
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getAllDocumentMetadataExtractionResultsCall(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next, final ApiCallback _callback) throws ApiException {
    String basePath = null;
    // Operation Servers
    String[] localBasePaths = new String[] {};

    // Determine Base Path to Use
    if (localCustomBaseUrl != null) {
      basePath = localCustomBaseUrl;
    } else if (localBasePaths.length > 0) {
      basePath = localBasePaths[localHostIndex];
    } else {
      basePath = null;
    }

    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/documents/{documentId}/metadataExtractionResults"
        .replace("{" + "documentId" + "}", localVarApiClient.escapeString(documentId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (siteId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("siteId", siteId));
    }

    if (artifactId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("artifactId", artifactId));
    }

    if (limit != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
    }

    if (next != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("next", next));
    }

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {};
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    if (localVarContentType != null) {
      localVarHeaderParams.put("Content-Type", localVarContentType);
    }

    String[] localVarAuthNames = new String[] {"AWS4Auth"};
    return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
        localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
        localVarFormParams, localVarAuthNames, _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call getAllDocumentMetadataExtractionResultsValidateBeforeCall(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next, final ApiCallback _callback) throws ApiException {
    // verify the required parameter 'documentId' is set
    if (documentId == null) {
      throw new ApiException(
          "Missing the required parameter 'documentId' when calling getAllDocumentMetadataExtractionResults(Async)");
    }

    return getAllDocumentMetadataExtractionResultsCall(documentId, siteId, artifactId, limit, next,
        _callback);

  }

  /**
   * Get all document&#39;s metadata extraction results Retrieve all document&#39;s metadata
   * extraction; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return GetDocumentMetadataExtractionResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public GetDocumentMetadataExtractionResponse getAllDocumentMetadataExtractionResults(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next) throws ApiException {
    ApiResponse<GetDocumentMetadataExtractionResponse> localVarResp =
        getAllDocumentMetadataExtractionResultsWithHttpInfo(documentId, siteId, artifactId, limit,
            next);
    return localVarResp.getData();
  }

  /**
   * Get all document&#39;s metadata extraction results Retrieve all document&#39;s metadata
   * extraction; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return ApiResponse&lt;GetDocumentMetadataExtractionResponse&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public ApiResponse<GetDocumentMetadataExtractionResponse> getAllDocumentMetadataExtractionResultsWithHttpInfo(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next) throws ApiException {
    okhttp3.Call localVarCall = getAllDocumentMetadataExtractionResultsValidateBeforeCall(
        documentId, siteId, artifactId, limit, next, null);
    Type localVarReturnType = new TypeToken<GetDocumentMetadataExtractionResponse>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * Get all document&#39;s metadata extraction results (asynchronously) Retrieve all document&#39;s
   * metadata extraction; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getAllDocumentMetadataExtractionResultsAsync(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next,
      final ApiCallback<GetDocumentMetadataExtractionResponse> _callback) throws ApiException {

    okhttp3.Call localVarCall = getAllDocumentMetadataExtractionResultsValidateBeforeCall(
        documentId, siteId, artifactId, limit, next, _callback);
    Type localVarReturnType = new TypeToken<GetDocumentMetadataExtractionResponse>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }

  /**
   * Build call for getDocumentDataClassification
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getDocumentDataClassificationCall(@javax.annotation.Nonnull String documentId,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next,
      final ApiCallback _callback) throws ApiException {
    String basePath = null;
    // Operation Servers
    String[] localBasePaths = new String[] {};

    // Determine Base Path to Use
    if (localCustomBaseUrl != null) {
      basePath = localCustomBaseUrl;
    } else if (localBasePaths.length > 0) {
      basePath = localBasePaths[localHostIndex];
    } else {
      basePath = null;
    }

    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/documents/{documentId}/dataClassification"
        .replace("{" + "documentId" + "}", localVarApiClient.escapeString(documentId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (siteId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("siteId", siteId));
    }

    if (artifactId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("artifactId", artifactId));
    }

    if (limit != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
    }

    if (next != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("next", next));
    }

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {};
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    if (localVarContentType != null) {
      localVarHeaderParams.put("Content-Type", localVarContentType);
    }

    String[] localVarAuthNames = new String[] {"AWS4Auth"};
    return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
        localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
        localVarFormParams, localVarAuthNames, _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call getDocumentDataClassificationValidateBeforeCall(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next, final ApiCallback _callback) throws ApiException {
    // verify the required parameter 'documentId' is set
    if (documentId == null) {
      throw new ApiException(
          "Missing the required parameter 'documentId' when calling getDocumentDataClassification(Async)");
    }

    return getDocumentDataClassificationCall(documentId, siteId, artifactId, limit, next,
        _callback);

  }

  /**
   * Get document&#39;s data classification Retrieve an document&#39;s data classification;
   * available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return GetDocumentDataClassificationResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public GetDocumentDataClassificationResponse getDocumentDataClassification(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next) throws ApiException {
    ApiResponse<GetDocumentDataClassificationResponse> localVarResp =
        getDocumentDataClassificationWithHttpInfo(documentId, siteId, artifactId, limit, next);
    return localVarResp.getData();
  }

  /**
   * Get document&#39;s data classification Retrieve an document&#39;s data classification;
   * available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return ApiResponse&lt;GetDocumentDataClassificationResponse&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public ApiResponse<GetDocumentDataClassificationResponse> getDocumentDataClassificationWithHttpInfo(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next) throws ApiException {
    okhttp3.Call localVarCall = getDocumentDataClassificationValidateBeforeCall(documentId, siteId,
        artifactId, limit, next, null);
    Type localVarReturnType = new TypeToken<GetDocumentDataClassificationResponse>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * Get document&#39;s data classification (asynchronously) Retrieve an document&#39;s data
   * classification; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getDocumentDataClassificationAsync(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId, @javax.annotation.Nullable String limit,
      @javax.annotation.Nullable String next,
      final ApiCallback<GetDocumentDataClassificationResponse> _callback) throws ApiException {

    okhttp3.Call localVarCall = getDocumentDataClassificationValidateBeforeCall(documentId, siteId,
        artifactId, limit, next, _callback);
    Type localVarReturnType = new TypeToken<GetDocumentDataClassificationResponse>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }

  /**
   * Build call for getDocumentMetadataExtractionResults
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getDocumentMetadataExtractionResultsCall(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next,
      final ApiCallback _callback) throws ApiException {
    String basePath = null;
    // Operation Servers
    String[] localBasePaths = new String[] {};

    // Determine Base Path to Use
    if (localCustomBaseUrl != null) {
      basePath = localCustomBaseUrl;
    } else if (localBasePaths.length > 0) {
      basePath = localBasePaths[localHostIndex];
    } else {
      basePath = null;
    }

    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/documents/{documentId}/metadataExtractionResults/{llmPromptEntityName}"
        .replace("{" + "documentId" + "}", localVarApiClient.escapeString(documentId.toString()))
        .replace("{" + "llmPromptEntityName" + "}",
            localVarApiClient.escapeString(llmPromptEntityName.toString()));

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (siteId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("siteId", siteId));
    }

    if (artifactId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("artifactId", artifactId));
    }

    if (limit != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
    }

    if (next != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("next", next));
    }

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {};
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    if (localVarContentType != null) {
      localVarHeaderParams.put("Content-Type", localVarContentType);
    }

    String[] localVarAuthNames = new String[] {"AWS4Auth"};
    return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
        localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
        localVarFormParams, localVarAuthNames, _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call getDocumentMetadataExtractionResultsValidateBeforeCall(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next,
      final ApiCallback _callback) throws ApiException {
    // verify the required parameter 'documentId' is set
    if (documentId == null) {
      throw new ApiException(
          "Missing the required parameter 'documentId' when calling getDocumentMetadataExtractionResults(Async)");
    }

    // verify the required parameter 'llmPromptEntityName' is set
    if (llmPromptEntityName == null) {
      throw new ApiException(
          "Missing the required parameter 'llmPromptEntityName' when calling getDocumentMetadataExtractionResults(Async)");
    }

    return getDocumentMetadataExtractionResultsCall(documentId, llmPromptEntityName, siteId,
        artifactId, limit, next, _callback);

  }

  /**
   * Get document&#39;s metadata extraction results Retrieve an document&#39;s metadata extraction;
   * available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return GetDocumentMetadataExtractionResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public GetDocumentMetadataExtractionResponse getDocumentMetadataExtractionResults(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next)
      throws ApiException {
    ApiResponse<GetDocumentMetadataExtractionResponse> localVarResp =
        getDocumentMetadataExtractionResultsWithHttpInfo(documentId, llmPromptEntityName, siteId,
            artifactId, limit, next);
    return localVarResp.getData();
  }

  /**
   * Get document&#39;s metadata extraction results Retrieve an document&#39;s metadata extraction;
   * available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @return ApiResponse&lt;GetDocumentMetadataExtractionResponse&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public ApiResponse<GetDocumentMetadataExtractionResponse> getDocumentMetadataExtractionResultsWithHttpInfo(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next)
      throws ApiException {
    okhttp3.Call localVarCall = getDocumentMetadataExtractionResultsValidateBeforeCall(documentId,
        llmPromptEntityName, siteId, artifactId, limit, next, null);
    Type localVarReturnType = new TypeToken<GetDocumentMetadataExtractionResponse>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * Get document&#39;s metadata extraction results (asynchronously) Retrieve an document&#39;s
   * metadata extraction; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param llmPromptEntityName LlmPrompt Entity Name (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param limit Limit Results (optional, default to 10)
   * @param next Next page of results token (optional)
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call getDocumentMetadataExtractionResultsAsync(
      @javax.annotation.Nonnull String documentId,
      @javax.annotation.Nonnull String llmPromptEntityName,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable String limit, @javax.annotation.Nullable String next,
      final ApiCallback<GetDocumentMetadataExtractionResponse> _callback) throws ApiException {

    okhttp3.Call localVarCall = getDocumentMetadataExtractionResultsValidateBeforeCall(documentId,
        llmPromptEntityName, siteId, artifactId, limit, next, _callback);
    Type localVarReturnType = new TypeToken<GetDocumentMetadataExtractionResponse>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }

  /**
   * Build call for setDocumentDataClassification
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param setDocumentDataClassificationRequest (optional)
   * @param _callback Callback for upload/download progress
   * @return Call to execute
   * @throws ApiException If fail to serialize the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call setDocumentDataClassificationCall(@javax.annotation.Nonnull String documentId,
      @javax.annotation.Nullable String siteId, @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable SetDocumentDataClassificationRequest setDocumentDataClassificationRequest,
      final ApiCallback _callback) throws ApiException {
    String basePath = null;
    // Operation Servers
    String[] localBasePaths = new String[] {};

    // Determine Base Path to Use
    if (localCustomBaseUrl != null) {
      basePath = localCustomBaseUrl;
    } else if (localBasePaths.length > 0) {
      basePath = localBasePaths[localHostIndex];
    } else {
      basePath = null;
    }

    Object localVarPostBody = setDocumentDataClassificationRequest;

    // create path and map variables
    String localVarPath = "/documents/{documentId}/dataClassification"
        .replace("{" + "documentId" + "}", localVarApiClient.escapeString(documentId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (siteId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("siteId", siteId));
    }

    if (artifactId != null) {
      localVarQueryParams.addAll(localVarApiClient.parameterToPair("artifactId", artifactId));
    }

    final String[] localVarAccepts = {"application/json"};
    final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
    if (localVarAccept != null) {
      localVarHeaderParams.put("Accept", localVarAccept);
    }

    final String[] localVarContentTypes = {"application/json"};
    final String localVarContentType =
        localVarApiClient.selectHeaderContentType(localVarContentTypes);
    if (localVarContentType != null) {
      localVarHeaderParams.put("Content-Type", localVarContentType);
    }

    String[] localVarAuthNames = new String[] {"AWS4Auth"};
    return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams,
        localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
        localVarFormParams, localVarAuthNames, _callback);
  }

  @SuppressWarnings("rawtypes")
  private okhttp3.Call setDocumentDataClassificationValidateBeforeCall(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable SetDocumentDataClassificationRequest setDocumentDataClassificationRequest,
      final ApiCallback _callback) throws ApiException {
    // verify the required parameter 'documentId' is set
    if (documentId == null) {
      throw new ApiException(
          "Missing the required parameter 'documentId' when calling setDocumentDataClassification(Async)");
    }

    return setDocumentDataClassificationCall(documentId, siteId, artifactId,
        setDocumentDataClassificationRequest, _callback);

  }

  /**
   * Set document&#39;s data classification Generate Data Classfication attributes within a
   * document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param setDocumentDataClassificationRequest (optional)
   * @return SetDocumentDataClassificationResponse
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public SetDocumentDataClassificationResponse setDocumentDataClassification(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable SetDocumentDataClassificationRequest setDocumentDataClassificationRequest)
      throws ApiException {
    ApiResponse<SetDocumentDataClassificationResponse> localVarResp =
        setDocumentDataClassificationWithHttpInfo(documentId, siteId, artifactId,
            setDocumentDataClassificationRequest);
    return localVarResp.getData();
  }

  /**
   * Set document&#39;s data classification Generate Data Classfication attributes within a
   * document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param setDocumentDataClassificationRequest (optional)
   * @return ApiResponse&lt;SetDocumentDataClassificationResponse&gt;
   * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
   *         response body
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public ApiResponse<SetDocumentDataClassificationResponse> setDocumentDataClassificationWithHttpInfo(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable SetDocumentDataClassificationRequest setDocumentDataClassificationRequest)
      throws ApiException {
    okhttp3.Call localVarCall = setDocumentDataClassificationValidateBeforeCall(documentId, siteId,
        artifactId, setDocumentDataClassificationRequest, null);
    Type localVarReturnType = new TypeToken<SetDocumentDataClassificationResponse>() {}.getType();
    return localVarApiClient.execute(localVarCall, localVarReturnType);
  }

  /**
   * Set document&#39;s data classification (asynchronously) Generate Data Classfication attributes
   * within a document; available as an Add-On Module
   * 
   * @param documentId Document Identifier (required)
   * @param siteId Site Identifier (optional)
   * @param artifactId Artifact Document Identifier (optional)
   * @param setDocumentDataClassificationRequest (optional)
   * @param _callback The callback to be executed when the API call finishes
   * @return The request call
   * @throws ApiException If fail to process the API call, e.g. serializing the request body object
   * @http.response.details
   *                        <table border="1">
   *                        <caption>Response Details</caption>
   *                        <tr>
   *                        <td>Status Code</td>
   *                        <td>Description</td>
   *                        <td>Response Headers</td>
   *                        </tr>
   *                        <tr>
   *                        <td>200</td>
   *                        <td>200 OK</td>
   *                        <td>* Access-Control-Allow-Origin - <br>
   *                        * Access-Control-Allow-Methods - <br>
   *                        * Access-Control-Allow-Headers - <br>
   *                        </td>
   *                        </tr>
   *                        </table>
   */
  public okhttp3.Call setDocumentDataClassificationAsync(
      @javax.annotation.Nonnull String documentId, @javax.annotation.Nullable String siteId,
      @javax.annotation.Nullable String artifactId,
      @javax.annotation.Nullable SetDocumentDataClassificationRequest setDocumentDataClassificationRequest,
      final ApiCallback<SetDocumentDataClassificationResponse> _callback) throws ApiException {

    okhttp3.Call localVarCall = setDocumentDataClassificationValidateBeforeCall(documentId, siteId,
        artifactId, setDocumentDataClassificationRequest, _callback);
    Type localVarReturnType = new TypeToken<SetDocumentDataClassificationResponse>() {}.getType();
    localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
    return localVarCall;
  }
}
